  name: YavlenaWorkflows
  on:
    pull_request:
      branches:
        - main
  jobs:
    selenium-tests:
      runs-on: ubuntu-latest

      services:
        selenium:
          image: selenium/standalone-chrome
          ports:
            - ""
    steps:
      - name: Checkout code
      - uses: actions/checkout@v3

      - name: Set up Java
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: ''

      - name: Run Tests
        run:
          mvn clean install
          mvn test
